version: "3"
networks:
  dbwebb:
services:
  test:
    image: periksson/microblog:test
    volumes:
      - "./:/home/microblog/app"
  prod:
    image: periksson/microblog:1.0.0-prod
    hostname: "microblog"
    ports:
      - "8000:5000"
    networks:
      dbwebb:
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://microblog:microblog@mysql/microblog"
  mysql:
    image: mysql/mysql-server:5.7
    hostname: mysql
    networks:
      dbwebb:
    environment:
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "microblog"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"